export const PLACEHOLDER_IMAGE = '//assets/images/common/placeholder.jpg';

const getPlaceholderImage = (id) => `https://i.pravatar.cc/300?img=${id}`;

export const teamCategories = [
  'Core Team',
  'Secretaries',
  'Event management',
  'Logistics',
  'Design',
  // 'Sponsorship',
  // 'Promotions',
  'Website',
];

export const teamMembers = [
  {
    id: 1,
    name: 'Vishal Raiyani',
    role: 'Event Management',
    category: 'Core Team',
    image: '/assets/images/Team/Vishalraiyani1.webp',
    description: 'Part of the Core Team handling overall event management.',
    quote: 'Efficiency is the key to success.',
  },
  {
    id: 2,
    name: 'Tina Josmon',
    role: 'Design and Creative',
    category: 'Core Team',
    image: '/assets/images/Team/TinaJosmon1.webp',
    description: 'Leading design and creative efforts for the event.',
  },
  {
    id: 3,
    name: 'Nigel Mondal',
    role: 'Logistics',
    category: 'Core Team',
    image: '/assets/images/Team/Nigel.webp',
    description: 'Ensuring smooth logistics for all aspects of the event.',
  },
  {
    id: 4,
    name: 'Akshit Jassuja',
    role: 'Promotions',
    category: 'Core Team',
    image:'/assets/images/Team/AkshitJasuja.webp',
    description: 'Managing promotions and outreach.',
  },
  {
    id: 5,
    name: 'Evelyn Tessy Emmanuel',
    role: 'Sponsorship',
    category: 'Core Team',
    image: '/assets/images/Team/evelyn.jpeg',
    description: 'Securing sponsorships and partnerships.',
  },
  {
    id: 6,
    name: 'Maanya Varma',
    role: 'Cultural Secretary',
    category: 'Core Team',
    image: '/assets/images/Team/Maanya.webp',
    description: 'Overseeing cultural activities.',
  },
  {
    id: 7,
    name: 'Dharani R Pillutla',
    role: 'Cultural Secretary',
    category: 'Core Team',
    image: '/assets/images/Team/Dharani _1.webp',
    description: 'Assisting in managing cultural events.',
  },
  {
    id: 8,
    name: 'Ann Denny Peter',
    role: 'Stage Head',
    category: 'Event management',
    image: '/assets/images/Team/Ann Denny Peter _2.webp',
  },
  {
    id: 9,
    name: 'Anna Mariam Prince',
    role: 'Literary Head',
    category: 'Event management',
    image: '/assets/images/Team/Anna Mariam Prince _2.webp',
  },
  {
    id: 10,
    name: 'Rohini K',
    role: 'Art Head',
    category: 'Event management',
    image: '/assets/images/Team/Rohini K 2.webp',
  },
  {
    id: 11,
    name: 'Archita kumari',
    role: 'Audi Head',
    category: 'Logistics',
    image: '/assets/images/Team/Archita Kumari 1.webp',
  },
  {
    id: 12,
    name: 'Atrayee Banerjee',
    role: 'Records Head',
    category: 'Logistics',
    image: '/assets/images/Team/Atrayee.webp',
  },
  {
    id: 13,
    name: 'Divyata Rohra',
    role: 'Literary Head',
    category: 'Event management',
    image: '/assets/images/Team/DivyataRohra.webp',
  },
  {
    id: 14,
    name: 'Shruti Sinha',
    role: 'Audi Head',
    category: 'Executive',
    image: '/assets/images/Team/Shruti Sinha_2.webp',
  },
  {
    id: 15,
    name: 'Varshita G',
    role: 'Hospitality Head',
    category: 'Logistics',
    image: '/assets/images/Team/Varshita G 2.webp',
  },
  {
    id: 16,
    name: 'Bhoomi Kansal',
    role: 'Records Head',
    category: 'Logistics',
    image: '/assets/images/Team/Bhoomi Kansal_1.webp',
  },
  {
    id: 17,
    name: 'Keerthi Santosh',
    role: 'Creative Head',
    category: 'Design',
    image: '/assets/images/Team/Keerthi 2.webp',
  },
  {
    id: 18,
    name: 'Mufti Sauleh',
    role: 'Media Head',
    category: 'Design',
    image: '/assets/images/Team/Sauleh_1.webp',
  },
  {
    id: 19,
    name: 'Joel Cherian Varghese',
    role: 'Emcee Head',
    category: 'Event management',
    image: '/assets/images/Team/Joel.webp',
  },
  {
    id: 20,
    name: 'Ananya Shanbhag',
    role: 'Dance Secretary',
    category: 'Secretaries',
    image: '/assets/images/Team/Ananya Shanbhag_2.webp',
  },
  {
    id: 21,
    name: 'Darsh Jain',
    role: 'Art Head',
    category: 'Event management',
    image: '/assets/images/Team/Darsh Jain_1.webp',
  },
  {
    id: 22,
    name: 'Ishaan Dhuria',
    role: 'Stage Head',
    category: 'Event management',
    image: '/assets/images/Team/Ishaan Dhuria_1.webp',
  },
  {
    id: 23,
    name: 'Sakshi Maghodaria',
    role: 'Art Secretary',
    category: 'Secretaries',
    image: '/assets/images/Team/SAKSHI MADHOGARIA.webp',
  },
  {
    id: 24,
    name: 'Garv Madan',
    role: 'Audi Head',
    category: 'Logistics',
    image: '/assets/images/Team/Garv Photo (2).webp',
  },
  {
    id: 25,
    name: 'Pranav Sajith',
    role: 'Literary Secretary',
    category: 'Secretaries',
    image: '/assets/images/Team/Pranav Sajith .webp',
  },
  {
    id: 26,
    name: 'Meera Salil',
    role: 'Music Secretary',
    category: 'Secretaries',
    image: getPlaceholderImage(27),
  },
  {
    id: 27,
    name: 'Paarth Maheshwari',
    role: 'Theatre Secretary',
    category: 'Secretaries',
    image: '/assets/images/Team/Paarth Maheshwari.webp',
  },
  {
    id: 28,
    name: 'Parthiv Ghosh',
    role: 'Esports Secretary',
    category: 'Secretaries',
    image: '/assets/images/Team/Parthiv Ghosh_2.webp',
  },
  {
    id: 29,
    name: 'Jitmanyu Nair',
    role: 'Literary Head',
    category: 'Event management',
    image: '/assets/images/Team/JITMANYU NAIR 2.webp',
  },
  {
    id: 30,
    name: 'Kamisetty Akshara',
    role: 'Stage Head',
    category: 'Event management',
    image: '/assets/images/Team/Kamisetty Akshara _2.webp',
  },
  {
    id: 31,
    name: 'Keerthana P',
    role: 'Hospitality Head',
    category: 'Logistics',
    image: '/assets/images/Team/Keerthana.webp',
  },

  {
    id: 34,
    name: 'NEVIL GEORGE NINAN',
    role: 'Media Head',
    category: 'Design',
    image: '/assets/images/Team/Nevil_1.webp',
  },
  {
    id: 35,
    name: 'Pavan K S',
    role: 'Creative Head',
    category: 'Design',
    image: '/assets/images/Team/Pavan K S _2.webp',
  },

  {
    id: 37,
    name: 'Sayatani Banerjee',
    role: 'Hospitality Head',
    category: 'Logistics',
    image: '/assets/images/Team/Sayantani.webp',
  },
  {
    id: 38,
    name: 'Shruti sinha',
    role: 'Audi Head',
    category: 'Logistics',
    image: '/assets/images/Team/Shruti Sinha_2.webp',
  },
  {
    id: 39,
    name: 'Titir Sinha',
    role: 'Creative Head',
    category: 'Design',
    image: '/assets/images/Team/TITIR SINHA_2.webp',
  },
  {
    id: 40,
    name: 'Treesa Alex',
    role: 'Emcee Head',
    category: 'Event management',
    image: '/assets/images/Team/Treesa Alex 2.webp',
  },
  {
    id: 41,
    name: 'Yashika P Reddy',
    role: 'Media Head',
    category: 'Design',
    image: '/assets/images/Team/Yashika P Reddy.webp',
  },
  {
    id: 42,
    name: 'Johan Dax',
    role: 'Emcee Head',
    category: 'Event management',
    image: '/assets/images/Team/Johan Dax.webp',
  },
  {
    id: 43,
    name: 'Annliya Sangeeth',
    role: 'Stage Head',
    category: 'Event management',
    image: '/assets/images/Team/ANNLIYA.webp',
  },
  {
    id: 44,
    name: 'Akansha Dey',
    role: 'Art Head',
    category: 'Event management',
    image: '/assets/images/Team/AkankshaDey .webp',
  },
  {
    id: 45,
    name: 'Tushar Ghosh',
    role: 'Web Developer',
    category: 'Website',
    image: '/assets/images/Team/tushar.webp',
  },
  {
    id: 46,
    name: 'Sumith meena',
    role: 'Web Developer',
    category: 'Core Team',
    image: '/assets/images/Team/sumith.webp',
  },
  {
    id: 47,
    name: 'Shrey Jain',
    role: 'Web Developer',
    category: 'Website',
    image: '/assets/images/Team/shrey.webp',
  },
  {
    id: 48,
    name: 'Agnitra Saha',
    role: 'Records Head',
    category: 'Logistics',
    image: '/assets/images/Team/Agnitra Saha Passport.webp',
  },
];
