export const PLACEHOLDER_IMAGE = '/src/assets/images/common/placeholder.jpg';

const getPlaceholderImage = (id) => `https://i.pravatar.cc/300?img=${id}`;

export const teamCategories = [
  'Core Team',
  'Event management',
  'Executive',
  'Engagement',
  'Sponsorship',
  'Promotions',
  'Website',
];

export const teamMembers = [
  {
    id: 1,
    name: 'Vishal Raiyani',
    role: 'Event Management',
    category: 'Core Team',
    image: 'src/assets/images/Team/Vishalraiyani1.JPG',
    description: 'Part of the Core Team handling overall event management.',
    quote: 'Efficiency is the key to success.',
  },
  {
    id: 2,
    name: 'Tina Josmon',
    role: 'Design and Creative',
    category: 'Core Team',
    image: 'src/assets/images/Team/TinaJosmon1.JPG',
    description: 'Leading design and creative efforts for the event.',
  },
  {
    id: 3,
    name: 'Nigel Mondal',
    role: 'Logistics',
    category: 'Core Team',
    image: 'src/assets/images/Team/NigelMondal3.JPG',
    description: 'Ensuring smooth logistics for all aspects of the event.',
  },
  {
    id: 4,
    name: 'Akshit Jassuja',
    role: 'Promotions',
    category: 'Core Team',
    image: 'src/assets/images/Team/AkshitJassuja4.JPG',
    description: 'Managing promotions and outreach.',
  },
  {
    id: 5,
    name: 'Evelyn Tessy Emmanuel',
    role: 'Sponsorship',
    category: 'Core Team',
    image: 'src/assets/images/Team/EvelynTessyEmmanuel5.JPG',
    description: 'Securing sponsorships and partnerships.',
  },
  {
    id: 6,
    name: 'Maanya Varma',
    role: 'Cultural Secretary',
    category: 'Core Team',
    image: 'src/assets/images/Team/EvelynTessyEmmanuel5.JPG',
    description: 'Overseeing cultural activities.',
  },
  {
    id: 7,
    name: 'Dharani R Pillutla',
    role: 'Cultural Secretary',
    category: 'Core Team',
    image: 'src/assets/images/Team/EvelynTessyEmmanuel5.JPG',
    description: 'Assisting in managing cultural events.',
  },
  {
    id: 8,
    name: 'Ann Denny Peter',
    role: 'Stage Head',
    category: 'Event management',
    image: 'src/assets/images/Team/Ann Denny Peter _2.JPG',
  },
  {
    id: 9,
    name: 'Anna Mariam Prince',
    role: 'Stage Head',
    category: 'Event management',
    image: 'src/assets/images/Team/Anna Mariam Prince _2.JPG',
  },
  {
    id: 10,
    name: 'Rohini K',
    role: 'Art Head',
    category: 'Event management',
    image: 'src/assets/images/Team/Rohini K 2.JPG',
  },
  {
    id: 11,
    name: 'Archita kumari',
    role: 'Art Head',
    category: 'Event Management',
    image: 'src/assets/images/Team/Archita Kumari 1.JPG',
  },
  {
    id: 12,
    name: 'Atrayee Banerjee',
    role: 'Art Head',
    category: 'Event Management',
    image: 'src/assets/images/Team/Atrayee.JPG',
  },
  {
    id: 13,
    name: 'Divyata Rohra',
    role: 'Literary Head',
    category: 'Event management',
    image: getPlaceholderImage(13),
  },
  {
    id: 14,
    name: 'Shruti Sinha',
    role: 'Audi Head',
    category: 'Executive',
    image: 'src/assets/images/Team/Shruti Sinha_2.JPG',
  },
  {
    id: 15,
    name: 'Varshita G',
    role: 'Hospitality Head',
    category: 'Executive',
    image: 'src/assets/images/Team/Varshita G 2.JPG',
  },
  {
    id: 16,
    name: 'Bhoomi Kansal',
    role: 'Records Head',
    category: 'Executive',
    image: 'src/assets/images/Team/Bhoomi Kansal_1.JPG',
  },
  {
    id: 17,
    name: 'Keerthi Santosh',
    role: 'Creative Head',
    category: 'Engagement',
    image: 'src/assets/images/Team/Keerthi 2.JPG',
  },
  {
    id: 18,
    name: 'Mufti Sauleh',
    role: 'Media Head',
    category: 'Engagement',
    image: getPlaceholderImage(18),
  },
  {
    id: 19,
    name: 'Joel Cherian Varghese',
    role: 'Emcee Head',
    category: 'Engagement',
    image: getPlaceholderImage(19),
  },
  {
    id: 20,
    name: 'Ananya Shanbhag',
    role: 'Dance Secretary',
    category: 'Secretaries',
    image: 'src/assets/images/Team/Ananya Shanbhag_2.JPG',
  },
  {
    id: 21,
    name: 'Darsh Jain',
    role: 'Dance Secretary',
    category: 'Event management',
    image: 'src/assets/images/Team/Darsh Jain_1.jpeg',
  },
  {
    id: 22,
    name: 'Ishaan Dhuria',
    role: 'Dance Secretary',
    category: 'Event management',
    image: 'src/assets/images/Team/Ishaan Dhuria_1.JPG',
  },
  {
    id: 23,
    name: 'Sakshi Maghodaria',
    role: 'Art Secretary',
    category: 'Secretaries',
    image: 'src/assets/images/Team/SAKSHI MADHOGARIA.JPG',
  },
  {
    id: 24,
    name: 'Garv Madan',
    role: 'Art Secretary',
    category: 'Secretaries',
    image: 'src/assets/images/Team/Garv Photo (2).JPG',
  },
  {
    id: 25,
    name: 'Pranav Sajith',
    role: 'Literary Secretary',
    category: 'Secretaries',
    image: 'src/assets/images/Team/Pranav Sajith .JPG',
  },
  {
    id: 26,
    name: 'Meera Salil',
    role: 'Music Secretary',
    category: 'Secretaries',
    image: getPlaceholderImage(26),
  },
  {
    id: 27,
    name: 'Paarth Maheshwari',
    role: 'Theatre Secretary',
    category: 'Secretaries',
    image: getPlaceholderImage(27),
  },
  {
    id: 28,
    name: 'Parthiv Ghosh',
    role: 'Esports Secretary',
    category: 'Secretaries',
    image: 'src/assets/images/Team/Parthiv Ghosh_2.JPG',
  },
  {
    id: 29,
    name: 'Jitmanyu Nair',
    role: 'Esports Secretary',
    category: 'Event management',
    image: 'src/assets/images/Team/JITMANYU NAIR 2.JPG',
  },
  {
    id: 30,
    name: 'Kamisetty Akshara',
    role: 'Esports Secretary',
    category: 'Event management',
    image: 'src/assets/images/Team/Kamisetty Akshara _2.JPG',
  },
  {
    id: 31,
    name: 'Keerthana P',
    role: 'Esports Secretary',
    category: 'Secretaries',
    image: 'src/assets/images/Team/Keerthana.JPG',
  },
  {
    id: 32,
    name: 'Keerthi Santosh',
    role: 'Esports Secretary',
    category: 'Secretaries',
    image: 'src/assets/images/Team/Keerthana.JPG',
  },
  {
    id: 33,
    name: 'Keerthi Santosh',
    role: 'Esports Secretary',
    category: 'Secretaries',
    image: 'src/assets/images/Team/Keerthi 2.JPG',
  },
  {
    id: 34,
    name: 'NEVIL GEORGE NINAN',
    role: 'Esports Secretary',
    category: 'Engagement',
    image: 'src/assets/images/Team/NEVIL GEORGE NINAN .JPG',
  },
  {
    id: 35,
    name: 'Pavan K S',
    role: 'Esports Secretary',
    category: 'Engagement',
    image: 'src/assets/images/Team/Pavan K S _2.JPG',
  },
  {
    id: 36,
    name: 'Pavan K S',
    role: 'Esports Secretary',
    category: 'Secretaries',
    image: 'src/assets/images/Team/Pavan K S _2.JPG',
  },
  {
    id: 37,
    name: 'Sayatani Banerjee',
    role: 'Esports Secretary',
    category: 'Secretaries',
    image: 'src/assets/images/Team/Sayantani.JPG',
  },
  {
    id: 38,
    name: 'Shruti sinha',
    role: 'Esports Secretary',
    category: 'Secretaries',
    image: 'src/assets/images/Team/Shruti Sinha_2.JPG',
  },
  {
    id: 39,
    name: 'Titir Sinha',
    role: 'Esports Secretary',
    category: 'Engagement',
    image: 'src/assets/images/Team/TITIR SINHA_2.JPG',
  },
  {
    id: 40,
    name: 'Treesa Alex',
    role: 'Esports Secretary',
    category: 'Engagement',
    image: 'src/assets/images/Team/Treesa Alex 2.JPG',
  },
  {
    id: 41,
    name: 'Yashika P Reddy',
    role: 'Esports Secretary',
    category: 'Engagement',
    image: 'src/assets/images/Team/Yashika P Reddy.JPG',
  },
  {
    id: 42,
    name: 'Johan Dax',
    role: 'Esports Secretary',
    category: 'Engagement',
    image: getPlaceholderImage(30) ,
  },
  {
    id: 43,
    name: 'Annliya Sangeeth',
    role: 'Esports Secretary',
    category: 'Event management',
    image: getPlaceholderImage(11),
  },
  {
    id: 44,
    name: 'Akansha Dey',
    role: 'Esports Secretary',
    category: 'Event management',
    image: getPlaceholderImage(12),
  },
  {
    id: 45,
    name: 'Tushar Ghosh',
    role: 'Esports Secretary',
    category: 'Website',
    image: getPlaceholderImage(8) ,
  },
  {
    id: 46,
    name: 'Sumit meena',
    role: 'Esports Secretary',
    category: 'Website',
    image: getPlaceholderImage(32) ,
  },
  {
    id: 47,
    name: 'Shrey Jain',
    role: 'Esports Secretary',
    category: 'Website',
    image: getPlaceholderImage(33) ,
  },
];
